// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoustafaTasks.Infrastructure;

#nullable disable

namespace MoustafaTasks.Infrastructure.Migrations
{
    [DbContext(typeof(TestingDbContext))]
    partial class TestingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoustafaTasks.Domain.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceType = "Camera",
                            IsActived = true,
                            IsRemoved = false,
                            NameEnglish = "Device1"
                        },
                        new
                        {
                            Id = 2,
                            DeviceType = "Another",
                            IsActived = false,
                            IsRemoved = false,
                            NameEnglish = "Device2"
                        },
                        new
                        {
                            Id = 3,
                            DeviceType = "Camera",
                            IsActived = false,
                            IsRemoved = true,
                            NameEnglish = "Device3"
                        });
                });

            modelBuilder.Entity("MoustafaTasks.Domain.SecUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("SecUsers", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            IsActived = true,
                            IsRemoved = false,
                            UserName = "username1",
                            UserTypeId = "Person"
                        },
                        new
                        {
                            UserId = 2,
                            IsActived = false,
                            IsRemoved = false,
                            UserName = "username2",
                            UserTypeId = "ServiceAccount"
                        },
                        new
                        {
                            UserId = 3,
                            IsActived = false,
                            IsRemoved = true,
                            UserName = "username3",
                            UserTypeId = "Person"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
